# We should eventually move staging and production to use PostgreSQL

development: &sqlite
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *sqlite
  database: db/test.sqlite3

cucumber:
  <<: *test

production:
  <<: *sqlite
  database: db/production.sqlite3