development: &sqlite
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *sqlite
  database: db/test.sqlite3

cucumber:
  <<: *test

production: &postgres
  adapter: postgresql
  database: dhaka
  username: postgres
  password: NL}2%/3 q-NgaKX[_cqf
  encoding: utf8
  pool: 5